---
- hosts: localhost
  connection: local
  become: true

  tasks:
    - name: install base packages
      package:
        name:
          - tmux
          - tree
          - htop
          - git
          - pass
          - ffmpeg

    - name: install stupid terminal nonsense
      package:
        name:
          - figlet
          - toilet

    - name: install neovim via appimage
      get_url:
        url: "https://github.com/neovim/neovim/releases/download/v0.4.4/nvim.appimage"
        dest: /usr/bin/nvim
        mode: 0755
      when: ansible_distribution in ["Debian", "Ubuntu"]

    - name: install neovim via homebrew
      package:
        name: neovim
      when: ansible_distribution == 'MacOSX'

    - name: sychronise dotfiles
      copy:
        src: 'files/dotfiles/{{ item.package }}/{{ item.path }}'
        dest: '/home/kaifahmed/{{ item.path }}'
        owner: kaifahmed
        group: kaifahmed
      loop:
        - { package: 'bash', path: '.bashrc' }
        - { package: 'bash', path: '.bash_profile' }
        - { package: 'bash', path: '.inputrc' }
        - { package: 'zsh', path: '.zshrc' }
        - { package: 'tmux', path: '.tmux.conf' }
        - { package: 'git', path: '.gitconfig' }
        - { package: 'gcs', path: '.customize_environment' }
        - { package: 'vim', path: '.vimrc' }
        - { package: 'vim', path: '.vim/coc-settings.json' }
        - { package: 'nvim', path: '.config/nvim/init.vim' }
        - { package: 'nvim', path: '.config/nvim/coc-settings.json' }
