---
- hosts: localhost
  connection: local
  become: true

  tasks:
    - name: install base packages
      package:
        name:
          - tmux
          - tree
          - htop
          - git
          - pass
          - ffmpeg
