---
- hosts: localhost
  connection: local
  vars_files:
    - vars/{{ ansible_distribution }}.yml

  tasks:
    - block:
      - name: install base packages
        tags: always
        package:
          name:
            - tmux
            - tree
            - htop
            - git
            - pass
            - ffmpeg
            - figlet
            - toilet
      become: '{{ should_be_root }}'

    - name: install neovim via appimage
      tags: dev
      get_url:
        url: "https://github.com/neovim/neovim/releases/download/v0.4.4/nvim.appimage"
        dest: /usr/bin/nvim
        mode: 0755
      when: ansible_distribution in ["Debian", "Ubuntu"]

    - block:
      - name: install neovim via homebrew
        tags: dev
        package:
          name: neovim
        when: ansible_distribution == 'MacOSX'
      become: '{{ should_be_root }}'

    - name: create required directories
      tags: always
      file:
        path: '{{ home_directory }}/{{ item }}'
        state: directory
        owner: '{{ owner }}'
        group: '{{ group }}'
        mode: 0755
      loop:
        - projects
        - playground
        - .vim
        - .config/nvim

    - name: sync dotfiles
      tags: always
      copy:
        src: 'files/dotfiles/{{ item.package }}/{{ item.path }}'
        dest: '{{ home_directory }}/{{ item.path }}'
        owner: '{{ owner }}'
        group: '{{ group }}'
      loop:
        - { package: 'bash', path: '.bashrc' }
        - { package: 'bash', path: '.bash_profile' }
        - { package: 'bash', path: '.inputrc' }
        - { package: 'zsh', path: '.zshrc' }
        - { package: 'tmux', path: '.tmux.conf' }
        - { package: 'git', path: '.gitconfig' }
        - { package: 'gcs', path: '.customize_environment' }
        - { package: 'vim', path: '.vimrc' }
        - { package: 'vim', path: '.vim/coc-settings.json' }
        - { package: 'nvim', path: '.config/nvim/init.vim' }
        - { package: 'nvim', path: '.config/nvim/coc-settings.json' }

    - name: remove init.sh script
      tags: always
      file:
        path: '{{ home_directory }}/init.sh'
        state: absent
