- name: app installation (Debian)
  tags: dev
  get_url:
    url: 'https://github.com/neovim/neovim/releases/download/nightly/nvim.appimage'
    dest: /usr/bin/nvim
    mode: 0755
  when: ansible_distribution in ['Debian', 'Ubuntu']

- name: app installation (Darwin)
  tags: dev
  homebrew:
    name: neovim
    state: head
  when: ansible_distribution == 'MacOSX'

- name: packer installation
  tags: dev
  git:
    repo: https://github.com/wbthomason/packer.nvim.git
    dest: '{{ home_directory }}/.local/share/nvim/site/pack/packer/start/packer.nvim'
